### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by YaliSx** [BlockResearchGroup/compas-IGS#1]
I am very interseted in Graphic Statics.I want to try to use your IGS plugin in Rhino. But I don't know how to install it in Rhino.Could you please tell me how to install it?I can't see your install instruction in GitBook, it shows I don't have permission.

**Comment by ricardoavelino** [comment]
Hi @YaliSx we are happy that you are interested in using `IGS`. We updated the docummentation and you can now see instructions to install it and a tutorial with a few examples. The link is this one: https://blockresearchgroup.gitbook.io/igs/ . Enjoy!
